# fly.toml app configuration file generated for site-giulia-gustavo on 2026-09-09T00:36:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'site-giulia-gustavo'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  ABACATEPAY_DEV = '0'
  DATABASE_SSL = 'disable'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
