-- 005 — famílias dos convidados

CREATE TABLE guest_family (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

INSERT INTO guest_family (id, name) VALUES
  (1, 'Familia Serginho'),
  (2, 'Familia Xandy'),
  (3, 'Familia Vó Iraci'),
  (4, 'Familia Vó Maria'),
  (5, 'Familia Vó Sara'),
  (6, 'familia Tio Beto'),
  (7, 'familia Tio Neto'),
  (8, 'Familia Tia Ruth'),
  (9, 'Familia Junior'),
  (10, 'Familia bia berlandi'),
  (11, 'Familia Tia Tutti'),
  (12, 'Familia Sabino'),
  (13, 'Familia Matheus Carvalho'),
  (14, 'Familia Assalim'),
  (15, 'Familia Bryan'),
  (16, 'Familia Giacomini'),
  (17, 'Familia Tio Miel'),
  (18, 'Familia Rita'),
  (19, 'Familia Tio Luiz'),
  (20, 'Familia Tia Angela'),
  (21, 'Familia Tio Lelo'),
  (22, 'Familia Bárbara'),
  (23, 'Familia Tio Lê'),
  (24, 'Familia do Lu'),
  (25, 'Familia Tia Daiane'),
  (26, 'Familia Tia Thaise'),
  (27, 'Familia Tia Renata'),
  (28, 'Familia Flávio Camargo'),
  (29, 'Familia Fátima Camargo')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- avança a sequência pra próxima inserção automática não colidir com os ids fixos
SELECT setval(
  pg_get_serial_sequence('guest_family', 'id'),
  (SELECT MAX(id) FROM guest_family)
);
